### ISSUE TITLE
[Enhancement] Recreate-Base-Shortcuts.ps1 - Reduce size for Intune

### ISSUE THREAD

**Issue by AlphaSeb** [TheAlienDrew/OS-Scripts#19]
Not really an issue with your scirpt, but thought I made you aware:

Selected file `Recreate-Base-Shortcut.ps1` must be between 1 and 200000 bytes.

Even with all comments and empty lines removed.

**Comment by TheAlienDrew** [comment]
I already have a couple ideas on how to solve this, but first I might ask, @AlphaSeb is it possible to upload files for Intune to use with `.ps1` scripts?

E.g. like a config file for `.msi` installers.

Because, if so, then I might just split the `.ps1` up into two files, the base script (all the main code needed), and the data for the shortcuts in a separate `.txt` file.

**Comment by TheAlienDrew** [comment]
> I already have a couple ideas on how to solve this, but first I might ask, @AlphaSeb is it possible to upload files for Intune to use with `.ps1` scripts?
> 
> E.g. like a config file for `.msi` installers.
> 
> Because, if so, then I might just split the `.ps1` up into two files, the base script (all the main code needed), and the data for the shortcuts in a separate `.txt` file.

I came up with a better idea, @AlphaSeb please use the new Intune ready script at:
- https://github.com/TheAlienDrew/OS-Scripts/blob/master/Windows/Microsoft-Endpoint-Defender/Recreate-Base-Shortcuts-INTUNE.ps1

**Comment by TheAlienDrew** [comment]
Closing, since now it should working with Intune, but creating a new request to reduce the size in general at: https://github.com/TheAlienDrew/OS-Scripts/issues/23
