### ISSUE TITLE
[Enhancement] Recreate-Base-Shortcuts.ps1 - Make warnings not report as errors

### ISSUE THREAD

**Issue by TheDarkLordRises** [TheAlienDrew/OS-Scripts#20]
The script is showing as Failed in intune, because each app that is not installed is failing like this:
```log
Visio
WARNING: Target invalid! Doesn't exist or is spelled wrong:
C:\Program Files\Microsoft Office\root\Office16\VISIO.EXE
```

That's for everything that's not installed. Log file is showing that it's creating those shortcuts which are missing, and skipping those that already exist. As a result (presumably that's why!), it's showing as failed in Device Status for all devices.

**Comment by AlphaSeb** [comment]
Intune doesnt like the output from the script and is reporting failure. I tried to remove those apps, so far I noticed etcher, balana and I think WinSpy:


error from script =New-Shortcut : Cannot bind argument to parameter 'sName' because it is an empty string.
At C:\Program Files (x86)\Microsoft Intune Management 
Extension\Policies\Scripts\e7ffa3d1-9e1e-465c-a180-64db6504e365_8587b248-0d2f-4ca2-b3b2-84d4aa9ba318.ps1:1384 char:36
+   $ScriptResults = New-Shortcut -n $aName -tp $aTargetPath -a $aArgum ...
+                                    ~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-Shortcut], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,New-Shortcut
 
New-Shortcut : Cannot bind argument to parameter 'sName' because it is an empty string.
At C:\Program Files (x86)\Microsoft Intune Management 
Extension\Policies\Scripts\e7ffa3d1-9e1e-465c-a180-64db6504e365_8587b248-0d2f-4ca2-b3b2-84d4aa9ba318.ps1:1384 char:36
+   $ScriptResults = New-Shortcut -n $aName -tp $aTargetPath -a $aArgum ...
+                                    ~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-Shortcut], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,New-Shortcut
 
-

I also noticed it's trying to create shortcuts at C:\Users\%HOSTNAME%\ when running with System Rights from Intune.
![image](https://user-images.githubusercontent.com/16120414/213184015-ca83d8d9-741b-443c-aaf7-d08f1a526aec.png)

**Comment by TheAlienDrew** [comment]
> The script is showing as Failed in Intune, because each app that is not installed is failing like this: Visio WARNING: Target invalid! Doesn't exist or is spelled wrong: C:\Program Files\Microsoft Office\root\Office16\VISIO.EXE
> 
> That's for everything that's not installed. Log file is showing that it's creating those shortcuts which are missing, and skipping those that already exist. As a result (presumably that's why!), it's showing as failed in Device Status for all devices.

This is the expected behavior, though I suppose I could make the script not report these as errors, and just as warnings only. I'll look into it.

**Comment by TheAlienDrew** [comment]
> Intune doesnt like the output from the script and is reporting failure. I tried to remove those apps, so far I noticed etcher, balana and I think WinSpy:
> 
> ```
> error from script =New-Shortcut : Cannot bind argument to parameter 'sName' because it is an empty string.
> At C:\Program Files (x86)\Microsoft Intune Management 
> Extension\Policies\Scripts\e7ffa3d1-9e1e-465c-a180-64db6504e365_8587b248-0d2f-4ca2-b3b2-84d4aa9ba318.ps1:1384 char:36
> +   $ScriptResults = New-Shortcut -n $aName -tp $aTargetPath -a $aArgum ...
> +                                    ~~~~~~
>     + CategoryInfo          : InvalidData: (:) [New-Shortcut], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,New-Shortcut
>  
> New-Shortcut : Cannot bind argument to parameter 'sName' because it is an empty string.
> At C:\Program Files (x86)\Microsoft Intune Management 
> Extension\Policies\Scripts\e7ffa3d1-9e1e-465c-a180-64db6504e365_8587b248-0d2f-4ca2-b3b2-84d4aa9ba318.ps1:1384 char:36
> +   $ScriptResults = New-Shortcut -n $aName -tp $aTargetPath -a $aArgum ...
> +                                    ~~~~~~
>     + CategoryInfo          : InvalidData: (:) [New-Shortcut], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,New-Shortcut
> 
> -
> ```
> 
> I also noticed it's trying to create shortcuts at C:\Users%HOSTNAME%\ when running with System Rights from Intune. ![image](https://user-images.githubusercontent.com/16120414/213184015-ca83d8d9-741b-443c-aaf7-d08f1a526aec.png)

This is a separate issue, see new issue created here: https://github.com/TheAlienDrew/OS-Scripts/issues/22

**Comment by TheAlienDrew** [comment]
Personal note: must not use `$errorMsg` or `Write-Error` when displaying warnings.

**Comment by TheAlienDrew** [comment]
@TheDarkLordRises, should be implemented now, since https://github.com/TheAlienDrew/OS-Scripts/commit/5b8dc66c7fc7a56ab5e51e328e71505dfe0446a9 now.

Though, I've heard some at least someone else that the script may be too big for Intune now (https://github.com/TheAlienDrew/OS-Scripts/issues/19), please let me know if that's the case.
