### ISSUE TITLE
[Bug] Recreate-Base-Shortcuts.ps1 - Empty Names in some instances

### ISSUE THREAD

**Issue by TheAlienDrew** [TheAlienDrew/OS-Scripts#22]
Intune doesnt like the output from the script and is reporting failure. I tried to remove those apps, so far I noticed etcher, balana and I think WinSpy:

1. ```log
   error from script =New-Shortcut : Cannot bind argument to parameter 'sName' because it is an empty string.
   At C:\Program Files (x86)\Microsoft Intune Management 
   Extension\Policies\Scripts\e7ffa3d1-9e1e-465c-a180-64db6504e365_8587b248-0d2f-4ca2-b3b2-84d4aa9ba318.ps1:1384 char:36
   +   $ScriptResults = New-Shortcut -n $aName -tp $aTargetPath -a $aArgum ...
   +                                    ~~~~~~
       + CategoryInfo          : InvalidData: (:) [New-Shortcut], ParameterBindingValidationException
       + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,New-Shortcut
 
   New-Shortcut : Cannot bind argument to parameter 'sName' because it is an empty string.
   At C:\Program Files (x86)\Microsoft Intune Management 
   Extension\Policies\Scripts\e7ffa3d1-9e1e-465c-a180-64db6504e365_8587b248-0d2f-4ca2-b3b2-84d4aa9ba318.ps1:1384 char:36
   +   $ScriptResults = New-Shortcut -n $aName -tp $aTargetPath -a $aArgum ...
   +                                    ~~~~~~
       + CategoryInfo          : InvalidData: (:) [New-Shortcut], ParameterBindingValidationException
       + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,New-Shortcut

   -
    ```

2. I also noticed it's trying to create shortcuts at C:\Users\\%HOSTNAME%\ when running with System Rights from Intune

3. <br>![image](https://user-images.githubusercontent.com/16120414/213184015-ca83d8d9-741b-443c-aaf7-d08f1a526aec.png)

_Originally posted by @AlphaSeb in https://github.com/TheAlienDrew/OS-Scripts/issues/20#issuecomment-1387077170_

_Edited by @TheAlienDrew to clarify points of interest (`2023-01-19T00:24:07Z`)_

**Comment by TheAlienDrew** [comment]
1. Did you try the latest version? Pretty sure I fixed this in https://github.com/TheAlienDrew/OS-Scripts/issues/16
2. Not sure what you mean by `C:\Users%HOSTNAME%`, but it could also be related to an old bug that I fixed. If you try the latest version of the script, do you still see that error?
3. I'll track down this issue...

**Comment by TheAlienDrew** [comment]
@AlphaSeb please test and respond when you have the chance.

**Comment by AlphaSeb** [comment]
It's still doing this, "ATPC-...." is the computername of the laptop where it's executed:

![image](https://user-images.githubusercontent.com/16120414/214843524-1d6e3ee3-bbfe-4cb7-af72-4edf70c147a8.png)

Still reporting as failure in Intune, even though the Log is created and script seems to run fine:

![image](https://user-images.githubusercontent.com/16120414/214844068-f11699ca-b030-4876-a564-5da7984a8553.png)


I suspect this beeing the issue:

<![LOG[error from script =Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Program Files (x86)\Microsoft Intune Management 
Extension\Policies\Scripts\e7ffa3d1-9e1e-465c-a180-64db6504e365_8587b248-0d2f-4ca2-b3b2-84d4aa9ba318.ps1:1429 char:44
+ $GIMP_ProductVersion = if (Test-Path -Path $GIMP_TargetPath -PathType ...
+                                            ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCom 
   mand
 
Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Program Files (x86)\Microsoft Intune Management 
Extension\Policies\Scripts\e7ffa3d1-9e1e-465c-a180-64db6504e365_8587b248-0d2f-4ca2-b3b2-84d4aa9ba318.ps1:1432 char:50
+ ... t_ProductVersion = if (Test-Path -Path $GIMP_32bit_TargetPath -PathTy ...
+                                            ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCom 
   mand
 
Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Program Files (x86)\Microsoft Intune Management 
Extension\Policies\Scripts\e7ffa3d1-9e1e-465c-a180-64db6504e365_8587b248-0d2f-4ca2-b3b2-84d4aa9ba318.ps1:1436 char:47
+ ... Pass_FileVersionRaw = if (Test-Path -Path $KeePass_TargetPath -PathTy ...
+                                               ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCom 
   mand
 
Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Program Files (x86)\Microsoft Intune Management 
Extension\Policies\Scripts\e7ffa3d1-9e1e-465c-a180-64db6504e365_8587b248-0d2f-4ca2-b3b2-84d4aa9ba318.ps1:1439 char:53
+ ... ileVersionRaw = if (Test-Path -Path $KeePass_32bit_TargetPath -PathTy ...
+                                         ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCom 
   mand
 
Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Program Files (x86)\Microsoft Intune Management 
Extension\Policies\Scripts\e7ffa3d1-9e1e-465c-a180-64db6504e365_8587b248-0d2f-4ca2-b3b2-84d4aa9ba318.ps1:1448 char:63
+ ... Raw = if (Test-Path -Path $VMwareWorkstationPlayer_TargetPath -PathTy ...
+                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCom 
   mand
 
Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\Program Files (x86)\Microsoft Intune Management 
Extension\Policies\Scripts\e7ffa3d1-9e1e-465c-a180-64db6504e365_8587b248-0d2f-4ca2-b3b2-84d4aa9ba318.ps1:1451 char:69
+ ... if (Test-Path -Path $VMwareWorkstationPlayer_32bit_TargetPath -PathTy ...
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCom 
   mand
 
New-Shortcut : Cannot bind argument to parameter 'sName' because it is an empty string.
At C:\Program Files (x86)\Microsoft Intune Management 
Extension\Policies\Scripts\e7ffa3d1-9e1e-465c-a180-64db6504e365_8587b248-0d2f-4ca2-b3b2-84d4aa9ba318.ps1:3781 char:40
+   $AttemptRecreation = New-Shortcut -n $aName -tp $aTargetPath -a $aA ...
+                                        ~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-Shortcut], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,New-Shortcut
 
New-Shortcut : Cannot bind argument to parameter 'sName' because it is an empty string.
At C:\Program Files (x86)\Microsoft Intune Management 
Extension\Policies\Scripts\e7ffa3d1-9e1e-465c-a180-64db6504e365_8587b248-0d2f-4ca2-b3b2-84d4aa9ba318.ps1:3781 char:40
+   $AttemptRecreation = New-Shortcut -n $aName -tp $aTargetPath -a $aA ...
+                                        ~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-Shortcut], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,New-Shortcut
 
New-Shortcut : Cannot bind argument to parameter 'sName' because it is an empty string.
At C:\Program Files (x86)\Microsoft Intune Management 
Extension\Policies\Scripts\e7ffa3d1-9e1e-465c-a180-64db6504e365_8587b248-0d2f-4ca2-b3b2-84d4aa9ba318.ps1:3781 char:40
+   $AttemptRecreation = New-Shortcut -n $aName -tp $aTargetPath -a $aA ...
+                                        ~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-Shortcut], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,New-Shortcut
 
New-Shortcut : Cannot bind argument to parameter 'sName' because it is an empty string.
At C:\Program Files (x86)\Microsoft Intune Management 
Extension\Policies\Scripts\e7ffa3d1-9e1e-465c-a180-64db6504e365_8587b248-0d2f-4ca2-b3b2-84d4aa9ba318.ps1:3781 char:40
+   $AttemptRecreation = New-Shortcut -n $aName -tp $aTargetPath -a $aA ...
+                                        ~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-Shortcut], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,New-Shortcut
 
New-Shortcut : Cannot bind argument to parameter 'sName' because it is an empty string.
At C:\Program Files (x86)\Microsoft Intune Management 
Extension\Policies\Scripts\e7ffa3d1-9e1e-465c-a180-64db6504e365_8587b248-0d2f-4ca2-b3b2-84d4aa9ba318.ps1:3781 char:40
+   $AttemptRecreation = New-Shortcut -n $aName -tp $aTargetPath -a $aA ...
+                                        ~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-Shortcut], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,New-Shortcut
 
New-Shortcut : Cannot bind argument to parameter 'sName' because it is an empty string.
At C:\Program Files (x86)\Microsoft Intune Management 
Extension\Policies\Scripts\e7ffa3d1-9e1e-465c-a180-64db6504e365_8587b248-0d2f-4ca2-b3b2-84d4aa9ba318.ps1:3781 char:40
+   $AttemptRecreation = New-Shortcut -n $aName -tp $aTargetPath -a $aA ...
+                                        ~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-Shortcut], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,New-Shortcut
 
New-Shortcut : Cannot bind argument to parameter 'sName' because it is an empty string.
At C:\Program Files (x86)\Microsoft Intune Management 
Extension\Policies\Scripts\e7ffa3d1-9e1e-465c-a180-64db6504e365_8587b248-0d2f-4ca2-b3b2-84d4aa9ba318.ps1:3781 char:40
+   $AttemptRecreation = New-Shortcut -n $aName -tp $aTargetPath -a $aA ...
+                                        ~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-Shortcut], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,New-Shortcut
 
New-Shortcut : Cannot bind argument to parameter 'sName' because it is an empty string.
At C:\Program Files (x86)\Microsoft Intune Management 
Extension\Policies\Scripts\e7ffa3d1-9e1e-465c-a180-64db6504e365_8587b248-0d2f-4ca2-b3b2-84d4aa9ba318.ps1:3781 char:40

**Comment by TheAlienDrew** [comment]
@AlphaSeb

For the `ATPC...` bit, that's expected if there's a user folder in `C:\Users\` named that, given that my script checks and adds missing shortcuts for all users on the device. So that's actually something that can be ignored.

As for the latter portion, I guess Sort-Object parameter `-Top` isn't available in older versions of PowerShell, so I reverted that code back to what I was using before. 🥲

Should be fixed with commit: https://github.com/TheAlienDrew/OS-Scripts/commit/475cdb7723ccfaa539ff45290d3d1c52473ae957

Give it a try and get back to me.

**Comment by TheAlienDrew** [comment]
@AlphaSeb I did some research, and I believe I found the issue, but it's not my script.

The reason why it shows your computer name in there in your user folders is because of a likely past corrupted profile. When a profile goes corrupt, it creates a new folder with the username and the hostname separated, but also if something happens (my guess is memory error) then it might also generate another corrupt profile, probably an edge case that created a usernameless corruption resolution user profile folder.

All other issues in this request have been long fixed by this time now, so going to resolve this.
